	<div class="card">
					<?PHP
					
						include('card_head_control.inc');
					
					?>

				<div class="card-body">
					
						<div class="row">
					
					<div class="col-lg-3">

							
								<div class="card bg-teal-400">
									<div class="card-body">
										<div class="d-flex">
											<h3 class="font-weight-semibold mb-0">5000</h3>
											<span class="badge bg-teal-800 badge-pill align-self-center ml-auto"><i class="icon-copy"></i></span>
					                	</div>
					                	
					                	<div>
											 Total Apartments
											
										</div>
									</div>

								
								</div>
							

							</div>
					         <div class="col-lg-3">

							
								<div class="card bg-success-400">
									<div class="card-body">
										<div class="d-flex">
											<h3 class="font-weight-semibold mb-0">2,543</h3>
											<span class="badge bg-success-800 badge-pill align-self-center ml-auto">30%</span>
					                	</div>
					                	
					                	<div>
											Total Vacant Apartments
											
										</div>
									</div>

								
								</div>
							

							</div>
					       
					
					       
					
					        <div class="col-lg-3">

							
								<div class="card bg-orange-400">
									<div class="card-body">
										<div class="d-flex">
											<h3 class="font-weight-semibold mb-0">120</h3>
											<span class="badge bg-orange-800 badge-pill align-self-center ml-auto">20%</span>
					                	</div>
					                	
    					                <div>
    										Total On Hold Apartments
    											
    									</div>
									</div>

									
								</div>
							

							</div>
							 <div class="col-lg-3">

							
								<div class="card bg-pink-400">
									<div class="card-body">
										<div class="d-flex">
											<h3 class="font-weight-semibold mb-0">3,125</h3>
											<span class="badge bg-pink-800 badge-pill align-self-center ml-auto">50%</span>
					                	</div>
					                	
					                	<div>
											 Total Sold Units
											
										</div>
									</div>

								
								</div>
							

							</div>
					
				        </div>
				        <br>
						<div class="row">
						    <div class="col-md-12">
								
								
								
								
								<!-- Daily sales -->
			        <div class="card">
							
                                
							<div class="table-responsive">
								<table class="table text-nowrap">
									<thead>
										<tr>
											<th class="w-100">Building Statistics</th>
											
											<th><span class="badge bg-success-400">Vacant</span></th>
											<th><span class="badge bg-orange-400">On Hold</span></th>
											<th><span class="badge bg-pink-400">Sold Units</span></th>
											<th><span class="badge bg-teal-400">Total Sales</span></th>
											<th><span class="badge bg-purple-400">Last Sale Details</span></th>
										</tr>
									</thead>
									<tbody>
										<tr>
											<td>
												<div class="d-flex align-items-center">
													<div class="mr-3">
														<a href="#" class="btn bg-primary-400 rounded-round btn-icon btn-sm">
															<span class="letter-icon"></span>
														</a>
													</div>
													<div>
														<a href="#" class="text-default font-weight-semibold letter-icon-title">Golden Tower</a>
														<div class="text-muted font-size-sm"><i class="icon-city font-size-sm mr-1"></i> Manama</div>
													</div>
												</div>
											</td>
										
											<td>
												<h6 class="font-weight-semibold mb-0">125</h6>
											</td>
											<td>
												<h6 class="font-weight-semibold mb-0">125</h6>
											</td>
											<td>
												<h6 class="font-weight-semibold mb-0">125</h6>
											</td>
											<td>
											<h6 class="font-weight-semibold mb-0">20,000.000 <small>BHD</small></h6>
											</td>
											<td>
											<h6 class="font-weight-semibold mb-0">3,000.000 <small>BHD   <b>on 05/02/2021</b></small></h6>
											</td>
										</tr>

										<tr>
											<td>
												<div class="d-flex align-items-center">
													<div class="mr-3">
														<a href="#" class="btn bg-warning-400 rounded-round btn-icon btn-sm">
															<span class="letter-icon"></span>
														</a>
													</div>
													<div>
														<a href="#" class="text-default font-weight-semibold letter-icon-title">Big Plaza</a>
														<div class="text-muted font-size-sm"><i class="icon-city font-size-sm mr-1"></i> Riffa</div>
													</div>
												</div>
											</td>
										
											<td>
												<h6 class="font-weight-semibold mb-0">525</h6>
											</td>
												<td>
												<h6 class="font-weight-semibold mb-0">525</h6>
											</td>
												<td>
												<h6 class="font-weight-semibold mb-0">525</h6>
											</td>
											<td>
											<h6 class="font-weight-semibold mb-0">20,000.000 <small>BHD</small></h6>
											</td>
											<td>
											<h6 class="font-weight-semibold mb-0">3,000.000 <small>BHD   <b>on 05/02/2021</b></small></h6>
											</td>
										</tr>

										<tr>
											<td>
												<div class="d-flex align-items-center">
													<div class="mr-3">
														<a href="#" class="btn bg-indigo-400 rounded-round btn-icon btn-sm">
															<span class="letter-icon"></span>
														</a>
													</div>
													<div>
														<a href="#" class="text-default font-weight-semibold letter-icon-title">Eagle Tower</a>
														<div class="text-muted font-size-sm"><i class="icon-city font-size-sm mr-1"></i> Sadid</div>
													</div>
												</div>
											</td>
										
											<td>
												<h6 class="font-weight-semibold mb-0">140</h6>
											</td>
											<td>
												<h6 class="font-weight-semibold mb-0">140</h6>
											</td>
											<td>
												<h6 class="font-weight-semibold mb-0">140</h6>
											</td>
											<td>
											<h6 class="font-weight-semibold mb-0">20,000.000 <small>BHD</small></h6>
											</td>
											<td>
											<h6 class="font-weight-semibold mb-0">5,000.000 <small>BHD   <b>on 07/02/2021</b></small></h6>
											</td>
										</tr>


									
									</tbody>
								</table>
							</div>
						</div>
						        <!-- /daily sales -->
								
								
								
								
								
								
								
								
							</div>

						    <div class="col-md-6">
								
								
								
								
								<!-- Daily sales -->
						        <!--<div class="card">
							
                                
							<div class="table-responsive">
								<table class="table text-nowrap">
									<thead>
										<tr>
											<th class="w-100">Customer Name and Contact Number</th>
											
											<th>Sold Price</th>
										</tr>
									</thead>
									<tbody>
										<tr>
											<td>
												<div class="d-flex align-items-center">
													<div class="mr-3">
														<a href="#" class="btn bg-primary-400 rounded-round btn-icon btn-sm">
															<span class="letter-icon"></span>
														</a>
													</div>
													<div>
														<a href="#" class="text-default font-weight-semibold letter-icon-title">Ancy Varghese</a>
														<div class="text-muted font-size-sm"><i class="icon-mobile font-size-sm mr-1"></i> 56222563</div>
													</div>
												</div>
											</td>
										
											<td>
												<h6 class="font-weight-semibold mb-0">15,000.000 <small>BHD</small></h6>
											</td>
										</tr>

										<tr>
											<td>
												<div class="d-flex align-items-center">
													<div class="mr-3">
														<a href="#" class="btn bg-danger-400 rounded-round btn-icon btn-sm">
															<span class="letter-icon"></span>
														</a>
													</div>
													<div>
														<a href="#" class="text-default font-weight-semibold letter-icon-title">Shebin</a>
														<div class="text-muted font-size-sm"><i class="icon-mobile font-size-sm mr-1"></i> 56332544</div>
													</div>
												</div>
											</td>
										
											<td>
												<h6 class="font-weight-semibold mb-0">18,000.000 <small>BHD</small></h6>
											</td>
										</tr>

										<tr>
											<td>
												<div class="d-flex align-items-center">
													<div class="mr-3">
														<a href="#" class="btn bg-success-400 rounded-round btn-icon btn-sm">
															<span class="letter-icon"></span>
														</a>
													</div>
													<div>
														<a href="#" class="text-default font-weight-semibold letter-icon-title">Sajin </a>
														<div class="text-muted font-size-sm"><i class="icon-mobile font-size-sm mr-1"></i> 562228596</div>
													</div>
												</div>
											</td>
										
											<td>
												<h6 class="font-weight-semibold mb-0">20,000.000 <small>BHD</small></h6>
											</td>
										</tr>


									
									</tbody>
								</table>
							</div>
						</div>-->
						        <!-- /daily sales -->
								
								
								
								
								
								
								
								
							</div>
				
						    <div class="col-md-12">
								
								
								
								
								
							<!-- Simple line chart -->
				            <div class="card">
					<div class="card-header header-elements-inline">
						<h5 class="card-title">Sales trends for last 4 months </h5>
						<div class="header-elements">
							<div class="list-icons">
		                		<a class="list-icons-item" data-action="collapse"></a>
		                		<a class="list-icons-item" data-action="reload"></a>
		                		<a class="list-icons-item" data-action="remove"></a>
		                	</div>
	                	</div>
					</div>

					<div class="card-body">
					
						<div class="chart-container">
							<div class="chart" id="google-line"></div>
						</div>
					</div>
				</div>
				            <!-- /simple line chart -->	
								
								
								
								
								
								
								
								
						</div>
				
						</div>
				</div>
					
	</div>
				