
		<div class="navbar-header navbar-dark d-none d-md-flex align-items-md-center">
		 
			<div style="width:250px" class="text-center">
			
		
		<span class=" " style="color:white;font-size: 17px;">THC FACILITY MANAGEMENT</span>
				<a href="#" class="d-inline-block">
				
				<!--	<img src="global_assets/images/logo_light.png" alt=""> -->
				</a>
			</div>
	
			<div class="navbar-brand navbar-brand-xs">
				<a href="#" class="d-inline-block">
					<img src="global_assets/images/logo_icon_light.png" alt="">
				</a>
			</div>
		</div>
		
		