
		<div class="collapse navbar-collapse" id="navbar-mobile">
		

			

			<ul class="navbar-nav">
			
			
				<li class="nav-item dropdown dropdown-user">
				        <span class="badge bg-pink-400 badge-pill ml-md-3 mr-md-auto" id="div_date_time">Date and Time </span>
				        <span class="badge bg-pink-400 badge-pill ml-md-3 mr-md-auto" id="client_ip">IP : <?PHP  echo $_SERVER['REMOTE_ADDR'];?></span>

				
				</li>
			</ul>
		</div>
		
		