		<div class="d-flex flex-1 d-md-none">
			<div class="navbar-brand mr-auto">
				<a href="dashboard.php" class="d-inline-block">
				<!--	<img src="global_assets/images/logo_dark.png" alt="">-->
					<span class=" " style="color:white;font-size: 17px;">THC FACILITY MANAGEMENT</span>
				</a>
			</div>

			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-mobile" style="color:white">
				<i class="icon-tree5"></i>
			</button>

			<button class="navbar-toggler sidebar-mobile-main-toggle" type="button" style="color:white">
				<i class="icon-paragraph-justify3"></i>
			</button>
		</div>