
				<div class="sidebar-user-material">
					<div class="sidebar-user-material-body">
						<div class="card-body text-center" style="height:140px;">
							
						</div>
													
						<!--<div class="sidebar-user-material-footer">
							<a href="#user-nav" class="d-flex justify-content-between align-items-center text-shadow-dark dropdown-toggle" data-toggle="collapse"><span>My account</span></a>
						</div>-->
					</div>
<!--
					<div class="collapse" id="user-nav">
						<ul class="nav nav-sidebar">
							<li class="nav-item">
								<a href="#" class="nav-link">
									<i class="icon-user-plus"></i>
									<span>My profile</span>
								</a>
							</li>
							
						
							<li class="nav-item">
								<a href="logout.php" class="nav-link" id="btn_sign_out">
									<i class="icon-switch2"></i>
									<span>Logout</span>
								</a>
							</li>
						</ul>
					</div>
				
				-->
				
				</div>
				