	<title>THC-FMS</title>

	<!-- Global stylesheets -->
	<link href="https://fonts.googleapis.com/css?family=Roboto:400,300,100,500,700,900" rel="stylesheet" type="text/css">
	<link href="../global_assets/css/icons/icomoon/styles.min.css" rel="stylesheet" type="text/css">
	
	<link href="../assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">

	<link href="../assets/css/bootstrap_limitless.min.css" rel="stylesheet" type="text/css">
	<link href="../assets/css/layout.min.css" rel="stylesheet" type="text/css">
	<link href="../assets/css/components.min.css" rel="stylesheet" type="text/css">
	<link href="../assets/css/colors.min.css" rel="stylesheet" type="text/css">
	<!-- /global stylesheets -->

	<!-- Core JS files-->
	<script src="../global_assets/js/main/jquery.min.js"></script> 

 
	<script src="../global_assets/js/main/bootstrap.bundle.min.js"></script>
	<script src="../global_assets/js/plugins/loaders/blockui.min.js"></script>
	<script src="../global_assets/js/plugins/ui/ripple.min.js"></script>
	<!-- /core JS files -->

	<!-- Theme JS files -->
	<script src="../global_assets/js/plugins/ui/prism.min.js"></script>

	<script src="../assets/js/app.js"></script>
	<!-- /theme JS files -->
	
	
	<script src="../global_assets/js/demo_pages/form_checkboxes_radios.js"></script>
	<script src="../global_assets/js/demo_pages/form_input_groups.js"></script>
	

    <!-- DataTables JavaScript -->
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.js"></script>
    <!-- User Permission Script -->
    <script type="text/javascript" src="js/jsfunctions.js?timestamp=<?php echo time(); ?>"></script>
